#pragma once

extern          char _binary_cubemapVS_glsl_end[];
extern          char _binary_cubemapFS_glsl_end[];
extern          char _binary_baseVS_glsl_end[];
extern          char _binary_baseFS_glsl_end[];
extern          char _binary_emerald_obj_end[];
extern          char _binary_cube_obj_end[];
extern unsigned char _binary_bot_png_end[];
extern unsigned char _binary_left_png_end[];
extern unsigned char _binary_back_png_end[];
extern unsigned char _binary_middle_png_end[];
extern unsigned char _binary_right_png_end[];
extern unsigned char _binary_top_png_end[];
extern unsigned char _binary_left_png_size[];
extern unsigned char _binary_middle_png_size[];
extern unsigned char _binary_right_png_size[];
extern unsigned char _binary_top_png_size[];
extern          char _binary_cubemapFS_glsl_size[];
extern          char _binary_baseVS_glsl_size[];
extern          char _binary_baseFS_glsl_size[];
extern          char _binary_emerald_obj_size[];
extern          char _binary_cube_obj_size[];
extern          char _binary_cubemapVS_glsl_size[];
extern unsigned char _binary_back_png_size[];
extern unsigned char _binary_bot_png_size[];
extern unsigned char _binary_back_png_start[];
extern unsigned char _binary_bot_png_start[];
extern unsigned char _binary_left_png_start[];
extern unsigned char _binary_middle_png_start[];
extern unsigned char _binary_right_png_start[];
extern unsigned char _binary_top_png_start[];
extern          char _binary_baseFS_glsl_start[];
extern          char _binary_baseVS_glsl_start[];
extern          char _binary_cubemapFS_glsl_start[];
extern          char _binary_cubemapVS_glsl_start[];
extern          char _binary_cube_obj_start[];
extern          char _binary_emerald_obj_start[];
extern unsigned char *back_png;
extern unsigned char *bot_png;
extern unsigned char *left_png;
extern unsigned char *middle_png;
extern unsigned char *right_png;
extern unsigned char *top_png;
extern          char *cube_obj;
extern          char *emerald_obj;
extern          char *baseFS_glsl;
extern          char *baseVS_glsl;
extern          char *cubemapFS_glsl;
extern          char *cubemapVS_glsl;
extern unsigned long back_png_len;
extern unsigned long bot_png_len;
extern unsigned long left_png_len;
extern unsigned long middle_png_len;
extern unsigned long right_png_len;
extern unsigned long top_png_len;
extern unsigned long baseFS_glsl_len;
extern unsigned long baseVS_glsl_len;
extern unsigned long cubemapFS_glsl_len;
extern unsigned long cubemapVS_glsl_len;
extern unsigned long cube_obj_len;
extern unsigned long emerald_obj_len;
